"""ser_lib：语音情感识别库。"""

__version__ = "0.2.0"

from ser_lib.core import Diagnostic, DiagnosticSeverity
from ser_lib.data import (
    CompatibilityReport,
    SERBatch,
    SERDataset,
    SERSample,
    TensorSpec,
    inspect_compatibility,
)
from ser_lib.artifacts import (
    ArtifactCatalog,
    ArtifactInfo,
    ArtifactScanFailure,
    ModelArtifactManifest,
    ModelCard,
    export_model_artifact,
    inspect_model_artifact,
    load_model_artifact,
    scan_model_artifacts,
    verify_model_artifact,
)
from ser_lib.engine import (
    EVALUATION_RUN_SCHEMA_VERSION,
    RUN_RECORD_SCHEMA_VERSION,
    EvaluationPredictionPage,
    EvaluationReportInfo,
    EvaluationRunCatalog,
    EvaluationRunInfo,
    EvaluationRunMetadata,
    EvaluationRunScanFailure,
    ExperimentConfig,
    ExperimentValidationResult,
    ModelConfig,
    ObservabilityConfig,
    Trainer,
    TrainerConfig,
    TrainingResult,
    TrainingRunCatalog,
    TrainingRunInfo,
    TrainingRunMetadata,
    TrainingRunScanFailure,
    TrainingStatus,
    build_evaluation_run_metadata,
    build_experiment_components,
    build_training_run_metadata,
    evaluate,
    inspect_evaluation_report,
    load_evaluation_run_info,
    load_training_run_info,
    query_evaluation_predictions,
    scan_evaluation_runs,
    scan_training_runs,
    validate_experiment,
    write_evaluation_report,
    write_evaluation_run_info,
    write_training_run_info,
)
from ser_lib.inference import (
    BatchEmotionPredictor,
    BatchPredictionResult,
    BatchPredictionSink,
    EmotionPredictor,
    JsonlBatchPredictionSink,
    PredictionFailure,
    PredictionResult,
    StreamingConfig,
    StreamingEmotionRecognizer,
    StreamingLatency,
    StreamingPrediction,
    write_batch_predictions,
)
from ser_lib.models import (
    CNNBaseline,
    GRUBaseline,
    HFAudioClassifier,
    ModelOutput,
    SERModel,
    TransformerBaseline,
)
from ser_lib.catalog import (
    CATALOG_CATEGORIES,
    CATALOG_SCHEMA_VERSION,
    ComponentCatalog,
    ComponentDescriptor,
    get_component_catalog,
    list_component_descriptors,
)
from ser_lib.runtime import (
    RuntimeCapabilities,
    RuntimeDevice,
    RuntimeMetrics,
    get_runtime_capabilities,
    get_runtime_metrics,
)

__all__ = [
    "Diagnostic", "DiagnosticSeverity",
    "CompatibilityReport", "inspect_compatibility",
    "CATALOG_SCHEMA_VERSION", "CATALOG_CATEGORIES",
    "ComponentDescriptor", "ComponentCatalog",
    "get_component_catalog", "list_component_descriptors",
    "RuntimeDevice", "RuntimeCapabilities", "RuntimeMetrics",
    "get_runtime_capabilities", "get_runtime_metrics",
    "SERDataset", "SERSample", "SERBatch", "TensorSpec",
    "ModelCard", "ModelArtifactManifest", "ArtifactInfo", "ArtifactScanFailure",
    "ArtifactCatalog", "scan_model_artifacts", "export_model_artifact",
    "inspect_model_artifact", "verify_model_artifact", "load_model_artifact",
    "SERModel", "ModelOutput", "CNNBaseline", "GRUBaseline",
    "TransformerBaseline", "HFAudioClassifier",
    "Trainer", "TrainerConfig", "ObservabilityConfig", "TrainingResult", "TrainingStatus",
    "TrainingRunMetadata", "build_training_run_metadata",
    "RUN_RECORD_SCHEMA_VERSION", "TrainingRunInfo", "TrainingRunScanFailure",
    "TrainingRunCatalog", "write_training_run_info", "load_training_run_info",
    "scan_training_runs",
    "EVALUATION_RUN_SCHEMA_VERSION", "EvaluationRunMetadata", "EvaluationRunInfo",
    "build_evaluation_run_metadata", "write_evaluation_run_info",
    "load_evaluation_run_info", "EvaluationRunScanFailure", "EvaluationRunCatalog",
    "scan_evaluation_runs",
    "EvaluationReportInfo", "EvaluationPredictionPage",
    "inspect_evaluation_report", "query_evaluation_predictions",
    "evaluate", "write_evaluation_report",
    "ExperimentConfig", "ExperimentValidationResult", "validate_experiment",
    "ModelConfig", "build_experiment_components",
    "EmotionPredictor", "PredictionResult",
    "PredictionFailure", "BatchPredictionSink", "JsonlBatchPredictionSink",
    "BatchPredictionResult", "BatchEmotionPredictor", "write_batch_predictions",
    "StreamingConfig", "StreamingPrediction", "StreamingLatency",
    "StreamingEmotionRecognizer",
]
